name: Flambe
pygments: true

blurbs:
    - title: Tastes Like Chicken
      body: Some extra text describing this feature and why it's amazing.

    - title: Tastes Like Beef
      body: Some extra text describing this feature and why it's amazing.

    - title: Tastes Like Pork
      body: Some extra text describing this feature and why it's amazing.

    - title: Tastes Like Fish
      body: Some extra text describing this feature and why it's amazing.

games:
    - title: Tweet Fighter
      url: http://tweetfighter.nl
      developer: <a href="https://mediamonks.com">MediaMonks</a>

    - title: Bubble Guppies&colon; Firefighters
      url: http://www.nickjr.com/kids-ad-entry.html?url=/kids-games/bubble-guppies-firefighters.html
      developer: <a href="http://seven2.net">Seven2</a>

    - title: Everybody Runs
      url: https://www.facebook.com/appcenter/everybodyruns
      developer: <a href="https://aduros.com">Bruno Garcia</a>

    - title: Space Date
      url: https://aduros.com/space-date
      developer: <a href="https://aduros.com">Bruno Garcia</a>

    - title: Another Game
      url: https://www.facebook.com/appcenter/everybodyruns
      developer: <a href="https://aduros.com">Bruno Garcia</a>

    - title: Another Game
      url: https://aduros.com/space-date
      developer: <a href="https://aduros.com">Bruno Garcia</a>

    - title: Another Game
      url: https://aduros.com/space-date
      developer: <a href="https://aduros.com">Bruno Garcia</a>
